### ISSUE TITLE
Very long ant build time

### ISSUE THREAD

**Issue by usptact** [sivareddyg/UDepLambda#17]
The `ant build` command takes hours and hours on my MBP 2012. The CPU is constantly 100% and switches occasionally from using all 4 cores to just one. Is it normal?

I ran all the commands to check out the repository and the respective submodules. No issues here (the download time was relatively long though).

No error messages are printed to the console. The current console output is:
```
$> ant build
Buildfile: /Users/vladislavsd/tools/UDepLambda/build.xml

build-subprojects:

init:
    [mkdir] Created dir: /Users/vladislavsd/tools/UDepLambda/bin

build-project:
     [echo] UDepLambda: /Users/vladislavsd/tools/UDepLambda/build.xml
    [javac] Compiling 30 source files to /Users/vladislavsd/tools/UDepLambda/bin
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.8
```

I am running Mac OS High Sierra 10.13.5
```
$> java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```
```
$> ant -version
Apache Ant(TM) version 1.10.1 compiled on February 2 2017
```

**Comment by usptact** [comment]
UPDATE:
The build failed after 523 minutes and 49 seconds with the following error message:

```
    [javac] The system is out of resources.
    [javac] Consult the following stack trace for details.
    [javac] java.lang.OutOfMemoryError: Java heap space
    [javac] 	at java.base/java.util.TimeZone.clone(TimeZone.java:754)
    [javac] 	at java.base/sun.util.calendar.ZoneInfo.clone(ZoneInfo.java:639)
    [javac] 	at java.base/java.util.TimeZone.getDefault(TimeZone.java:643)
    [javac] 	at java.base/java.time.ZoneId.systemDefault(ZoneId.java:272)
    [javac] 	at jdk.zipfs/jdk.nio.zipfs.ZipUtils.dosToJavaTime(ZipUtils.java:117)
    [javac] 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$Entry.cen(ZipFileSystem.java:1950)
    [javac] 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$Entry.readCEN(ZipFileSystem.java:1937)
    [javac] 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.getEntry(ZipFileSystem.java:1324)
    [javac] 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.getFileAttributes(ZipFileSystem.java:312)
    [javac] 	at jdk.zipfs/jdk.nio.zipfs.ZipPath.getAttributes(ZipPath.java:721)
    [javac] 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:293)
    [javac] 	at java.base/java.nio.file.Files.readAttributes(Files.java:1755)
    [javac] 	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
    [javac] 	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
    [javac] 	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373)
    [javac] 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2749)
    [javac] 	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager$ArchiveContainer.<init>(JavacFileManager.java:523)
    [javac] 	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getContainer(JavacFileManager.java:319)
    [javac] 	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.list(JavacFileManager.java:715)
    [javac] 	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.list(ClassFinder.java:722)
    [javac] 	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.scanUserPaths(ClassFinder.java:655)
    [javac] 	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:526)
    [javac] 	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:293)
    [javac] 	at jdk.compiler/com.sun.tools.javac.code.ClassFinder$$Lambda$48/263885523.complete(Unknown Source)
    [javac] 	at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:633)
    [javac] 	at jdk.compiler/com.sun.tools.javac.code.Symbol$PackageSymbol.members(Symbol.java:1120)
    [javac] 	at jdk.compiler/com.sun.tools.javac.code.Symtab.listPackageModules(Symtab.java:810)
    [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Enter.visitTopLevel(Enter.java:344)
    [javac] 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:529)
    [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Enter.classEnter(Enter.java:285)
    [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Enter.classEnter(Enter.java:300)
    [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Enter.complete(Enter.java:570)

BUILD FAILED
/Users/vladislavsd/tools/UDepLambda/build.xml:101: Compile failed; see the compiler error output for details.
```

**Comment by sivareddyg** [comment]
Strange, never had any problems. The build should complete in less than 1 minute. Can you retry increasing your heap size.

**Comment by usptact** [comment]
@sivareddyg Thanks for looking into this. I tried again on a beefier machine and everything worked. Thanks!
