### ISSUE TITLE
NoClassDefFoundError in the Freebase experiment

### ISSUE THREAD

**Issue by marcwww** [sivareddyg/UDepLambda#22]
Dear author, I am trying to reproduce the results of the Freebase experiments. There is a really weird issue boring me: when I tried to get the oracle graphs:
```make extract_gold_graphs_bow_en-bilty-bist```,
a 'NoClassDefFoundError' exception was thrown:
```
mkdir -p data/gold_graphs/
cat data/WebQuestions/en/en-bilty-bist-webquestions.train.deplambda.json \
        data/WebQuestions/en/en-bilty-bist-webquestions.dev.deplambda.json \
    | java -Dfile.encoding="UTF-8" -cp bin:lib/* in.sivareddy.scripts.EvaluateGraphParserOracleUsingGoldMidAndGoldRelations \
        data/freebase/schema/all_domains_schema.txt localhost \
        bow_question_graph \
        data/gold_graphs/en-bilty-bist_bow_without_merge_without_expand.full \
        lib_data/dummy.txt \
        false \
        false \
        > data/gold_graphs/en-bilty-bist_bow_without_merge_without_expand.full.answers.txt
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/jena/graph/impl/GraphBase
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at in.sivareddy.graphparser.util.RdfGraphTools.<init>(RdfGraphTools.java:83)
	at in.sivareddy.graphparser.util.RdfGraphTools.<init>(RdfGraphTools.java:78)
	at in.sivareddy.scripts.EvaluateGraphParserOracleUsingGoldMidAndGoldRelations.<init>(EvaluateGraphParserOracleUsingGoldMidAndGoldRelations.java:83)
	at in.sivareddy.scripts.EvaluateGraphParserOracleUsingGoldMidAndGoldRelations.main(EvaluateGraphParserOracleUsingGoldMidAndGoldRelations.java:414)
Caused by: java.lang.ClassNotFoundException: org.apache.jena.graph.impl.GraphBase
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 17 more
make: *** [extract_gold_graphs_bow_en-bilty-bist] Error 1 
```
This is weird since 'org/apache/jena/graph/impl/GraphBase' exists only in the higher version of jena-core-3.xx.jar but the jena-core-2.13.0.jar in the lib folder of this project.

I am using MacOS Mojave 10.14 and java 1.8.0_251.

I would appreciate it a lot if you can help me with this.

**Comment by sivareddyg** [comment]
This code is no longer maintained. Moreover, this won't run without running a virtuoso server. 

If all you require is graphs corresponding to these queries, check this file:

https://bitbucket.org/sivareddyg/webquestions/src/master/en/en-stanford-stanford-webquestions.dev.deplambda.json

All you need is "goldRelations" and "entities" keys. Also checkout training and test splits.
